version: "3"
services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    command: redis-server --requirepass root
  phoneBook:
    ports:
      - '3001:3001'
    build:
      context: './'
      dockerfile: 'dockerfile'
      target: 'builder'
    restart: 'unless-stopped'
    volumes:
      - .:/home/node
      - /home/node/node_modules
    command: sh -c "node dist/main.js"
    env_file:
      - 'local.env'
    depends_on:
      - mysql
      - redis
