export const contacts = [
  {
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '0534567890',
    address: '123 Main St',
    isFavorite: true,
    imageUrl: 'https://example.com/image1.jpg',
    email: 'john.doe@example.com',
  },
  {
    firstName: 'Jane',
    lastName: 'Doe',
    phoneNumber: '0587654321',
    address: '456 Elm St',
    isFavorite: false,
    imageUrl: 'https://example.com/image2.jpg',
    email: 'Jane.doe@example.com',
  },
  {
    firstName: 'Alice',
    lastName: 'Smith',
    phoneNumber: '0576543210',
    address: '789 Oak St',
    isFavorite: true,
    imageUrl: 'https://example.com/image3.jpg',
    notes: 'Met at the conference last week.',
  },
  {
    firstName: 'Bob',
    lastName: 'Johnson',
    phoneNumber: '0555555555',
    address: '321 Pine St',
    isFavorite: false,
    imageUrl: 'https://example.com/image4.jpg',
    email: 'bob.jones@example.com',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    phoneNumber: '0512223333',
    address: '456 Maple St',
    isFavorite: true,
    imageUrl: 'https://example.com/image5.jpg',
    email: 'michael.brown@example.com',
  },
  {
    firstName: 'Emily',
    lastName: 'Taylor',
    phoneNumber: '0598887777',
    address: '789 Elm St',
    isFavorite: false,
    imageUrl: 'https://example.com/image6.jpg',
    notes: 'Sent follow-up email regarding project details.',
  },
  {
    firstName: 'William',
    lastName: 'Miller',
    phoneNumber: '0545556666',
    address: '123 Oak St',
    isFavorite: true,
    imageUrl: 'https://example.com/image7.jpg',
    notes: 'Scheduled meeting for next Monday.',
  },
  {
    firstName: 'Olivia',
    lastName: 'Johnson',
    phoneNumber: '0578889999',
    address: '321 Cedar St',
    isFavorite: false,
    imageUrl: 'https://example.com/image8.jpg',
    notes: 'Discussed new marketing strategy.',
  },
  {
    firstName: 'James',
    lastName: 'Wilson',
    phoneNumber: '0534445555',
    address: '456 Birch St',
    isFavorite: true,
    imageUrl: 'https://example.com/image9.jpg',
    notes: 'Received feedback from client.',
  },
  {
    firstName: 'Sophia',
    lastName: 'Moore',
    phoneNumber: '0567778888',
    address: '789 Pine St',
    isFavorite: false,
    imageUrl: 'https://example.com/image10.jpg',
    notes: 'Sent proposal for new project.',
  },
  {
    firstName: 'David',
    lastName: 'Jones',
    phoneNumber: '0531231234',
    address: '789 Cedar St',
    isFavorite: true,
    imageUrl: 'https://example.com/image11.jpg',
    notes: 'Completed training session.',
  },
  {
    firstName: 'Emma',
    lastName: 'White',
    phoneNumber: '0564564567',
    address: '321 Maple St',
    isFavorite: false,
    imageUrl: 'https://example.com/image12.jpg',
    email: 'Emma.White@example.com',
  },
  {
    firstName: 'Daniel',
    lastName: 'Martinez',
    phoneNumber: '0597897890',
    address: '123 Elm St',
    isFavorite: true,
    imageUrl: 'https://example.com/image13.jpg',
    email: 'Daniel.Martinez@example.com',
  },
  {
    firstName: 'Chloe',
    lastName: 'Garcia',
    phoneNumber: '0579879876',
    address: '456 Oak St',
    isFavorite: false,
    imageUrl: 'https://example.com/image14.jpg',
    notes: 'Shared presentation slides with team.',
  },
  {
    firstName: 'Ethan',
    lastName: 'Lopez',
    phoneNumber: '0546546543',
    address: '789 Cedar St',
    isFavorite: true,
    imageUrl: 'https://example.com/image15.jpg',
    email: 'Ethan.Lopez@example.com',
    notes: 'Received positive feedback from manager.',
  },
  {
    firstName: 'Madison',
    lastName: 'Young',
    phoneNumber: '0213213210',
    address: '123 Maple St',
    isFavorite: false,
    imageUrl: 'https://example.com/image16.jpg',
    email: 'Madison.Young@example.com',
  },
  {
    firstName: 'Ava',
    lastName: 'Hernandez',
    phoneNumber: '0112223333',
    address: '123 Pine St',
    isFavorite: true,
    imageUrl: 'https://example.com/image17.jpg',
    notes: 'Attended networking event.',
  },
  {
    firstName: 'Noah',
    lastName: 'King',
    phoneNumber: '0445556666',
    address: '456 Birch St',
    isFavorite: false,
    imageUrl: 'https://example.com/image18.jpg',
    notes: 'Met with potential client.',
  },
  {
    firstName: 'Mia',
    lastName: 'Wright',
    phoneNumber: '0778889999',
    address: '789 Cedar St',
    isFavorite: true,
    imageUrl: 'https://example.com/image19.jpg',
    notes: 'Reviewed project requirements.',
  },
  {
    firstName: 'Liam',
    lastName: 'Gonzalez',
    phoneNumber: '0334445555',
    address: '123 Elm St',
    isFavorite: false,
    imageUrl: 'https://example.com/image20.jpg',
    notes: 'Reviewed latest quarterly report.',
  },
  {
    firstName: 'Isabella',
    lastName: 'Perez',
    phoneNumber: '0667778888',
    address: '456 Oak St',
    isFavorite: true,
    imageUrl: 'https://example.com/image21.jpg',
    email: 'Isabella.Perez@example.com',
  },
  {
    firstName: 'Lucas',
    lastName: 'Roberts',
    phoneNumber: '0998887777',
    address: '789 Maple St',
    isFavorite: false,
    imageUrl: 'https://example.com/image22.jpg',
    email: 'Lucas.Roberts@example.com',
  },
];
