export const contacts = [
  {
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '1234567890',
    address: '123 Main St',
    isFavorite: true,
    imageUrl: 'https://example.com/image1.jpg',
  },
  {
    firstName: 'Jane',
    lastName: 'Doe',
    phoneNumber: '0987654321',
    address: '456 Elm St',
    isFavorite: false,
    imageUrl: 'https://example.com/image2.jpg',
  },
  {
    firstName: 'Alice',
    lastName: 'Smith',
    phoneNumber: '9876543210',
    address: '789 Oak St',
    isFavorite: true,
    imageUrl: 'https://example.com/image3.jpg',
  },
  {
    firstName: 'Bob',
    lastName: 'Johnson',
    phoneNumber: '5555555555',
    address: '321 Pine St',
    isFavorite: false,
    imageUrl: 'https://example.com/image4.jpg',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    phoneNumber: '1112223333',
    address: '456 Maple St',
    isFavorite: true,
    imageUrl: 'https://example.com/image5.jpg',
  },
  {
    firstName: 'Emily',
    lastName: 'Taylor',
    phoneNumber: '9998887777',
    address: '789 Elm St',
    isFavorite: false,
    imageUrl: 'https://example.com/image6.jpg',
  },
  {
    firstName: 'William',
    lastName: 'Miller',
    phoneNumber: '4445556666',
    address: '123 Oak St',
    isFavorite: true,
    imageUrl: 'https://example.com/image7.jpg',
  },
  {
    firstName: 'Olivia',
    lastName: 'Johnson',
    phoneNumber: '7778889999',
    address: '321 Cedar St',
    isFavorite: false,
    imageUrl: 'https://example.com/image8.jpg',
  },
  {
    firstName: 'James',
    lastName: 'Wilson',
    phoneNumber: '3334445555',
    address: '456 Birch St',
    isFavorite: true,
    imageUrl: 'https://example.com/image9.jpg',
  },
  {
    firstName: 'Sophia',
    lastName: 'Moore',
    phoneNumber: '6667778888',
    address: '789 Pine St',
    isFavorite: false,
    imageUrl: 'https://example.com/image10.jpg',
  },
  {
    firstName: 'David',
    lastName: 'Jones',
    phoneNumber: '1231231234',
    address: '789 Cedar St',
    isFavorite: true,
    imageUrl: 'https://example.com/image11.jpg',
  },
  {
    firstName: 'Emma',
    lastName: 'White',
    phoneNumber: '4564564567',
    address: '321 Maple St',
    isFavorite: false,
    imageUrl: 'https://example.com/image12.jpg',
  },
  {
    firstName: 'Daniel',
    lastName: 'Martinez',
    phoneNumber: '7897897890',
    address: '123 Elm St',
    isFavorite: true,
    imageUrl: 'https://example.com/image13.jpg',
  },
  {
    firstName: 'Chloe',
    lastName: 'Garcia',
    phoneNumber: '9879879876',
    address: '456 Oak St',
    isFavorite: false,
    imageUrl: 'https://example.com/image14.jpg',
  },
  {
    firstName: 'Ethan',
    lastName: 'Lopez',
    phoneNumber: '6546546543',
    address: '789 Cedar St',
    isFavorite: true,
    imageUrl: 'https://example.com/image15.jpg',
  },
  {
    firstName: 'Madison',
    lastName: 'Young',
    phoneNumber: '3213213210',
    address: '123 Maple St',
    isFavorite: false,
    imageUrl: 'https://example.com/image16.jpg',
  },
  {
    firstName: 'Ava',
    lastName: 'Hernandez',
    phoneNumber: '1112223333',
    address: '123 Pine St',
    isFavorite: true,
    imageUrl: 'https://example.com/image17.jpg',
  },
  {
    firstName: 'Noah',
    lastName: 'King',
    phoneNumber: '4445556666',
    address: '456 Birch St',
    isFavorite: false,
    imageUrl: 'https://example.com/image18.jpg',
  },
  {
    firstName: 'Mia',
    lastName: 'Wright',
    phoneNumber: '7778889999',
    address: '789 Cedar St',
    isFavorite: true,
    imageUrl: 'https://example.com/image19.jpg',
  },
  {
    firstName: 'Liam',
    lastName: 'Gonzalez',
    phoneNumber: '3334445555',
    address: '123 Elm St',
    isFavorite: false,
    imageUrl: 'https://example.com/image20.jpg',
  },
  {
    firstName: 'Isabella',
    lastName: 'Perez',
    phoneNumber: '6667778888',
    address: '456 Oak St',
    isFavorite: true,
    imageUrl: 'https://example.com/image21.jpg',
  },
  {
    firstName: 'Lucas',
    lastName: 'Roberts',
    phoneNumber: '9998887777',
    address: '789 Maple St',
    isFavorite: false,
    imageUrl: 'https://example.com/image22.jpg',
  },
];
